name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

env:
  CAPAWESOME_CLI_VERSION: 4.6.0
  NODE_VERSION: 22

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Authenticate with Capawesome Cloud
        run: npx @capawesome/cli@${{ env.CAPAWESOME_CLI_VERSION }} login --token ${{ secrets.CAPAWESOME_CLOUD_TOKEN }}
      - name: Build Android
        run: |
          npx @capawesome/cli@${{ env.CAPAWESOME_CLI_VERSION }} apps:builds:create \
            --app-id ${{ secrets.CAPAWESOME_CLOUD_APP_ID }} \
            --platform android \
            --type release \
            --git-ref ${{ github.sha }} \
            --certificate "Production" \
            --yes
  build-ios:
    name: Build iOS
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Authenticate with Capawesome Cloud
        run: npx @capawesome/cli@${{ env.CAPAWESOME_CLI_VERSION }} login --token ${{ secrets.CAPAWESOME_CLOUD_TOKEN }}
      - name: Build iOS
        run: |
          npx @capawesome/cli@${{ env.CAPAWESOME_CLI_VERSION }} apps:builds:create \
            --app-id ${{ secrets.CAPAWESOME_CLOUD_APP_ID }} \
            --platform ios \
            --type app-store \
            --git-ref ${{ github.sha }} \
            --certificate "Production" \
            --yes
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set npm token
        run: echo "//npm.registry.capawesome.io/:_authToken=${{ secrets.CAPAWESOME_NPM_REGISTRY_TOKEN }}" >> .npmrc
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run ESLint and Prettier
        run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set npm token
        run: echo "//npm.registry.capawesome.io/:_authToken=${{ secrets.CAPAWESOME_NPM_REGISTRY_TOKEN }}" >> .npmrc
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:ci
  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Set npm token
        run: echo "//npm.registry.capawesome.io/:_authToken=${{ secrets.CAPAWESOME_NPM_REGISTRY_TOKEN }}" >> .npmrc
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run end-to-end tests
        run: npm run e2e:ci
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: cypress/screenshots
